Examen_ToolsForEver/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_ToolsForEver.Models
{
    public class Product
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public int ProductLocatieID { get; set; }

        [Required]
        public int FabrikantID { get; set; }

        //[Required]
        //public int LocatieID { get; set; }

        [Required]
        public string Naam { get; set; }

        public string Type { get; set; }

        [Required]
        public decimal InkoopWaarde { get; set; }

        [Required]
        public decimal VerkoopWaarde { get; set; }

        public Fabrikant Fabrikant { get; set; }
        public List<ProductLocatie> ProductLocaties { get; set; }

    }
}

Examen_ToolsForEver/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Examen_ToolsForEver.Data;
using Examen_ToolsForEver.Models;
using Examen_ToolsForEver.Models.AccountViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Examen_ToolsForEver.Models.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Examen_ToolsForEver.Controllers
{
    public class ApplicationUsersController : BasicController
    {
        public ApplicationUsersController(UserManager<ApplicationUser> _userManager, ApplicationDbContext dbcontext, RoleManager<IdentityRole> roleManager) : base(_userManager, dbcontext, roleManager)
        {
        }

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            var model = new List<UserListViewModel>();
            model = _userManager.Users.Select(u => new UserListViewModel
            {
                Id = u.Id,
                Name = u.UserName
            }).ToList();

            return View(model);
        }

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _dbcontext.ApplicationUser
                .SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            RegisterViewModel model = new RegisterViewModel();
            model.ApplicationRoles = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            return View(model);
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(RegisterViewModel registerModel)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = registerModel.UserName
                };
                IdentityResult result = await _userManager.CreateAsync(user, registerModel.Password);
                if (result.Succeeded)
                {
                    IdentityRole identityRole = await _roleManager.FindByIdAsync(registerModel.ApplicationRoleId);
                    if (identityRole != null)
                    {
                        IdentityResult roleResult = await _userManager.AddToRoleAsync(user, identityRole.Name);
                        if (roleResult.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            return View(registerModel);
        }

        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            EditUserViewModel model = new EditUserViewModel();
            model.ApplicationRoles = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser user = await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    model.UserName = user.UserName;
                    model.ApplicationRoleId = _roleManager.Roles.Single(r => r.Name == _userManager.GetRolesAsync(user).Result.Single()).Id;
                }
            }
            return View(model);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    user.UserName = model.UserName;
                    user.Email = model.Email;
                    string existingRole = _userManager.GetRolesAsync(user).Result.Single();
                    string existingRoleId = _roleManager.Roles.Single(r => r.Name == existingRole).Id;
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        if (existingRoleId != model.ApplicationRoleId)
                        {
                            IdentityResult roleResult = await _userManager.RemoveFromRoleAsync(user, existingRole);
                            if (roleResult.Succeeded)
                            {
                                IdentityRole applicationRole = await _roleManager.FindByIdAsync(model.ApplicationRoleId);
                                if (applicationRole != null)
                                {
                                    IdentityResult newRoleResult = await _userManager.AddToRoleAsync(user, applicationRole.Name);
                                    if (newRoleResult.Succeeded)
                                    {
                                        return RedirectToAction("Index");
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return PartialView("_EditUser", model);
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            string userName = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser applicationUser = await _userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    userName = applicationUser.UserName;
                }
            }

            return View(userName);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, FormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser applicationUser = await _userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    IdentityResult result = await _userManager.DeleteAsync(applicationUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }

        private bool ApplicationUserExists(string id)
        {
            return _dbcontext.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

Examen_ToolsForEver/Controllers/ProductLocatiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Examen_ToolsForEver.Data;
using Examen_ToolsForEver.Models;

namespace Examen_ToolsForEver.Controllers
{
    public class ProductLocatiesController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;

        public ProductLocatiesController(ApplicationDbContext context)
        {
            _dbcontext = context;    
        }

        // GET: ProductLocaties
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _dbcontext.ProductLocatie.Include(p => p.Locatie).Include(p => p.Product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProductLocaties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productLocatie = await _dbcontext.ProductLocatie
                .Include(p => p.Locatie)
                .Include(p => p.Product)
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (productLocatie == null)
            {
                return NotFound();
            }

            return View(productLocatie);
        }

        // GET: ProductLocaties/Create
        public IActionResult Create()
        {
            ViewData["LocatieID"] = new SelectList(_dbcontext.Locaties, "ID", "LocatieNaam");
            ViewData["ProductID"] = new SelectList(_dbcontext.Producten, "ID", "Naam");
            return View();
        }

        // POST: ProductLocaties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Aantal,MinVoorraad,LocatieID,ProductID")] ProductLocatie productLocatie)
        {
            if (ModelState.IsValid)
            {
                _dbcontext.Add(productLocatie);
                await _dbcontext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["LocatieID"] = new SelectList(_dbcontext.Locaties, "ID", "LocatieNaam", productLocatie.LocatieID);
            ViewData["ProductID"] = new SelectList(_dbcontext.Producten, "ID", "Naam", productLocatie.ProductID);
            return View(productLocatie);
        }

        // GET: ProductLocaties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productLocatie = await _dbcontext.ProductLocatie.SingleOrDefaultAsync(m => m.ProductID == id);
            if (productLocatie == null)
            {
                return NotFound();
            }
            ViewData["LocatieID"] = new SelectList(_dbcontext.Locaties, "ID", "LocatieNaam", productLocatie.LocatieID);
            ViewData["ProductID"] = new SelectList(_dbcontext.Producten, "ID", "Naam", productLocatie.ProductID);
            return View(productLocatie);
        }

        // POST: ProductLocaties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Aantal,MinVoorraad,LocatieID,ProductID")] ProductLocatie productLocatie)
        {
            if (id != productLocatie.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbcontext.Update(productLocatie);
                    await _dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductLocatieExists(productLocatie.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["LocatieID"] = new SelectList(_dbcontext.Locaties, "ID", "LocatieNaam", productLocatie.LocatieID);
            ViewData["ProductID"] = new SelectList(_dbcontext.Producten, "ID", "Naam", productLocatie.ProductID);
            return View(productLocatie);
        }

        // GET: ProductLocaties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productLocatie = await _dbcontext.ProductLocatie
                .Include(p => p.Locatie)
                .Include(p => p.Product)
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (productLocatie == null)
            {
                return NotFound();
            }

            return View(productLocatie);
        }

        // POST: ProductLocaties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productLocatie = await _dbcontext.ProductLocatie.SingleOrDefaultAsync(m => m.ProductID == id);
            _dbcontext.ProductLocatie.Remove(productLocatie);
            await _dbcontext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProductLocatieExists(int id)
        {
            return _dbcontext.ProductLocatie.Any(e => e.ProductID == id);
        }
    }
}

Examen_ToolsForEver/Views/Products/Create.cshtml
@model Examen_ToolsForEver.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ProductLocatieID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @*<input asp-for="ProductLocatieID" class="form-control" />
                <span asp-validation-for="ProductLocatieID" class="text-danger"></span>*@
                <select asp-for="ProductLocatieID" asp-items="@ViewBag.LocationID" class="form-control">
                    <option>--Selecteer--</option>
                </select>

            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fabrikant" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="FabrikantID" class ="form-control" asp-items="ViewBag.FabrikantID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Naam" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="InkoopWaarde" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="InkoopWaarde" class="form-control" />
                <span asp-validation-for="InkoopWaarde" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="VerkoopWaarde" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="VerkoopWaarde" class="form-control" />
                <span asp-validation-for="VerkoopWaarde" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen_ToolsForEver/Views/Products/Delete.cshtml
@model Examen_ToolsForEver.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.ProductLocatieID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductLocatieID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InkoopWaarde)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InkoopWaarde)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerkoopWaarde)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerkoopWaarde)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fabrikant)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fabrikant.FabrikantNaam)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Examen_ToolsForEver/Views/Products/Details.cshtml
@model Examen_ToolsForEver.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductLocatieID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductLocatieID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InkoopWaarde)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InkoopWaarde)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerkoopWaarde)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerkoopWaarde)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fabrikant)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fabrikant.FabrikantNaam)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Examen_ToolsForEver/Views/Products/Edit.cshtml
@model Examen_ToolsForEver.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="ProductLocatieID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ProductLocatieID" asp-items="@ViewBag.LocationID" class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FabrikantID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="FabrikantID" class="form-control" asp-items="ViewBag.FabrikantID"></select>
                <span asp-validation-for="FabrikantID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Naam" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="InkoopWaarde" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="InkoopWaarde" class="form-control" />
                <span asp-validation-for="InkoopWaarde" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="VerkoopWaarde" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="VerkoopWaarde" class="form-control" />
                <span asp-validation-for="VerkoopWaarde" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen_ToolsForEver/Views/Products/Index.cshtml
@model Examen_ToolsForEver.Models.ViewModels.ProductIndexData

@{
    ViewData["Title"] = "Index";
}

<header class="header">
    <a asp-controller="ProductLocaties" asp-action="Index" class="btn btn-default">Producten (voorraad)</a>
    <a asp-controller="ApplicationUsers" asp-action="Index" class="btn btn-default">Gebruikers</a>
</header>

<h2>Producten</h2>

<p>
    <a asp-action="Create" class="btn btn-default">Create New</a>
</p>

<div>
    <form asp-action="Index" method="post" class="form-inline">
        <span style="display:block;">Zoek op naam of ID</span>
        <input name="searchValue" value="@ViewData["searchValue"]" placeholder="zoeken..." class="form-control" />
        <input type="submit" value="zoeken" class="btn btn-default" />
    </form>
</div>


@foreach (var test in Model.Locaties)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Fabriek
                </th>
                <th>
                    Type
                </th>
                <th>
                    Voorraad
                </th>
                <th>
                    Minimale voorraad
                </th>
                <th>
                    Locatie
                </th>
                <th>
                    Inkoopprijs
                </th>
                <th>
                    Verkoopprijs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProductLocaties)
            {
                //testID locatieID
                if (test.ID.Equals(item.LocatieID))
                {
                    var totalewaarde = item.Aantal * item.Product.VerkoopWaarde;
                    <div style="text-align:right; font-size: 24px">
                        @Model.LocationTotalValue waarde locatie: <b>@item.Locatie.LocatieNaam</b> @totalewaarde
                    </div>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Naam)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Fabrikant.FabrikantNaam)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Type)
                        </td>
                        <td class="@item.VoorraadCheck()">
                            @Html.DisplayFor(modelItem => item.Aantal)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MinVoorraad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Locatie.LocatieNaam)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.InkoopWaarde)
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.Product.VerkoopWaarde)
                        </th>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ProductID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}